#!/usr/bin/env node
import { Command } from "commander";
import inquirer from "inquirer";
import { access, chmod, mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";
import { commandRun } from "./blueprinter-run/blueprinter-run";

type Template = "node-cli" | "readme";
type PackageManager = "npm" | "pnpm" | "yarn";

type Defaults = {
  template: Template;
  projectName: string;
  targetDir: string;
  initGit: boolean;
  packageManager: PackageManager;
};

type Config = Defaults;

const pathExists = async (p: string) => {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
};

const ensureEmptyDir = async (dir: string) => {
  if (!(await pathExists(dir))) {
    await mkdir(dir, { recursive: true });
    return;
  }
  const entries = await readdir(dir);
  if (entries.length > 0) throw new Error(`Target directory is not empty: ${dir}`);
};

const toValidPackageName = (name: string) => {
  const cleaned = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-_.]/g, "-")
    .replace(/^-+/, "")
    .replace(/-+$/, "");

  return cleaned.length ? cleaned : "my-app";
};

const writeFileSafe = async (filePath: string, contents: string) => {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, contents, "utf8");
};

const tryGitInit = async (cwd: string) => {
  await new Promise<void>((resolve) => {
    const p = spawn("git", ["init"], { cwd, stdio: "ignore" });
    p.on("close", () => resolve());
    p.on("error", () => resolve());
  });
};

const scaffoldNodeCli = async (config: Config) => {
  const absTargetDir = path.resolve(process.cwd(), config.targetDir);
  await ensureEmptyDir(absTargetDir);

  const pkgName = toValidPackageName(config.projectName);

  await writeFileSafe(
    path.join(absTargetDir, "README.md"),
    `# ${config.projectName}\n\nGenerated by \`blueprinter\`.\n`
  );

  await writeFileSafe(path.join(absTargetDir, ".gitignore"), `node_modules\n.DS_Store\n.env\n`);

  await writeFileSafe(
    path.join(absTargetDir, "package.json"),
    JSON.stringify(
      {
        name: pkgName,
        version: "0.1.0",
        private: true,
        type: "commonjs",
        bin: { [pkgName]: "bin/cli.js" },
        scripts: { start: "node bin/cli.js" }
      },
      null,
      2
    ) + "\n"
  );

  const cliPath = path.join(absTargetDir, "bin", "cli.js");
  await writeFileSafe(
    cliPath,
    `#!/usr/bin/env node
console.log("Hello from ${config.projectName}!");
`
  );
  await chmod(cliPath, 0o755);

  if (config.initGit) await tryGitInit(absTargetDir);

  const installStep =
    config.packageManager === "npm"
      ? "npm install"
      : config.packageManager === "pnpm"
        ? "pnpm install"
        : "yarn";
  const startStep =
    config.packageManager === "npm"
      ? "npm start"
      : config.packageManager === "pnpm"
        ? "pnpm start"
        : "yarn start";

  return {
    absTargetDir,
    nextSteps: [`cd ${config.targetDir}`, installStep, startStep],
  };
};

const scaffoldReadmeOnly = async (config: Config) => {
  const absTargetDir = path.resolve(process.cwd(), config.targetDir);
  await ensureEmptyDir(absTargetDir);

  await writeFileSafe(
    path.join(absTargetDir, "README.md"),
    `# ${config.projectName}\n\nThis folder was created by \`blueprinter\`.\n`
  );

  return {
    absTargetDir,
    nextSteps: [`cd ${config.targetDir}`],
  };
};

const runInteractive = async (defaults: Defaults, yes: boolean): Promise<Config> => {
  if (yes) return defaults;

  const answers = await inquirer.prompt<{
    template: Template;
    projectName: string;
    targetDir: string;
    initGit?: boolean;
    packageManager?: PackageManager;
  }>([
    {
      type: "list",
      name: "template",
      message: "What should I generate?",
      choices: [
        { name: "Node CLI app (hello world)", value: "node-cli" },
        { name: "README-only folder", value: "readme" },
      ],
      default: defaults.template,
    },
    {
      type: "input",
      name: "projectName",
      message: "Project name:",
      default: defaults.projectName,
      validate: (v) => (String(v ?? "").trim().length ? true : "Please enter a project name"),
    },
    {
      type: "input",
      name: "targetDir",
      message: "Target directory (relative to current folder):",
      default: (a: { projectName: string }) => defaults.targetDir || toValidPackageName(a.projectName),
      validate: (v) => (String(v ?? "").trim().length ? true : "Please enter a target directory"),
    },
    {
      type: "confirm",
      name: "initGit",
      message: "Initialize a git repository?",
      default: defaults.initGit,
      when: (a) => a.template === "node-cli",
    },
    {
      type: "list",
      name: "packageManager",
      message: "Package manager for next steps:",
      choices: [
        { name: "npm", value: "npm" },
        { name: "pnpm", value: "pnpm" },
        { name: "yarn", value: "yarn" },
      ],
      default: defaults.packageManager,
      when: (a) => a.template === "node-cli",
    },
  ]);

  return {
    template: answers.template,
    projectName: answers.projectName,
    targetDir: answers.targetDir,
    initGit: answers.initGit ?? defaults.initGit,
    packageManager: answers.packageManager ?? defaults.packageManager,
  };
};





const main = async () => {
  const program = new Command();

  program
    .name("blueprinter")
    .description("Interactive CLI for project blueprints")
    .showHelpAfterError("(add --help for usage)");

  program
    .command("run")
    .description("Create a project from a blueprint source")
    .action(commandRun);

  //TODO: add later
  // program
  //   .command("add")
  //   .description("Add a small markdown file in the current directory")
  //   .option("-y, --yes", "skip prompts and use a default title", false)
  //   .option("-f, --file <name>", "filename to create", "blueprinter-note.md")
  //   .action(async (cmdOpts) => {
  //     try {
  //       await cmdAdd(cmdOpts);
  //     } catch (err) {
  //       console.error((err as Error)?.message ?? String(err));
  //       process.exitCode = 1;
  //     }
  //   });

  await program.parseAsync(process.argv);
}

void main();
